from typing import List
from app.models import TemplateField

# Define TemplateField objects with keyword arguments
test_name_fields: List[TemplateField] = [
    TemplateField(field_name="Complete Blood Count", keywords=["complete blood count", "cbc"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="RBC Count", keywords=["rbc count"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Hemoglobin", keywords=["hemoglobin", "hb", "hgb", 'HAEMOGLOBIN (Hb)'], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Packed Cell Volume", keywords=["pcv", "packed cell volume"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Platelet Count", keywords=["platelet count", "plt"," PLATELET COUNT"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Neutrophils", keywords=["neutrophils"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Lymphocytes", keywords=["lymphocytes"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Eosinophils", keywords=["eosinophils"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Monocytes", keywords=["monocytes"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Basophils", keywords=["basophils"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Mylocytes", keywords=["mylocytes"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Blast", keywords=["blast"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Metamylocytes", keywords=["metamylocytes"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Mean Platelet Volume (MPV)", keywords=["mpv", "mean platelet volume"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="INR", keywords=["inr"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="White Blood Cell Count (WBC)", keywords=["wbc", "white blood cell count"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Mean Corpuscular Volume (MCV)", keywords=["mcv"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Mean Corpuscular Hemoglobin (MCH)", keywords=["mch"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Mean Corpuscular Hemoglobin Concentration (MCHC)", keywords=["mchc"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Reticulocyte Count", keywords=["reticulocyte count"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Hemoglobin A1c", keywords=["hemoglobin a1c"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Peripheral Blood Smear", keywords=["peripheral blood smear"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Blood Film Examination", keywords=["blood film examination"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Erythrocyte Sedimentation Rate (ESR)", keywords=["esr"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="C-Reactive Protein (CRP)", keywords=["crp"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Platelet Distribution Width (PDW)", keywords=["pdw"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Platelet Crit (PCT)", keywords=["pct"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Pancytopenia", keywords=["pancytopenia"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Bone Marrow Aspiration", keywords=["bone marrow aspiration"], field_type="numeric", section="Haematology"),
    TemplateField(field_name="Lactate Dehydrogenase (LDH)", keywords=["ldh"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Haptoglobin", keywords=["haptoglobin"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Vitamin B12", keywords=["vitamin b12"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Folate", keywords=["folate"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Iron Studies", keywords=["iron studies"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Serum Iron", keywords=["serum iron"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Ferritin", keywords=["ferritin"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Total Iron Binding Capacity (TIBC)", keywords=["tibc"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Transferrin Saturation", keywords=["transferrin saturation"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Sodium", keywords=["sodium"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Potassium", keywords=["potassium"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Chloride", keywords=["chloride"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Calcium", keywords=["calcium"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Magnesium", keywords=["magnesium"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Phosphate", keywords=["phosphate"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Urea", keywords=["urea"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Creatinine", keywords=["creatinine"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Uric Acid", keywords=["uric acid"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Glucose", keywords=["glucose", "blood sugar", "sugar"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Random Blood Sugar (RBS)", keywords=["rbs"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Fasting Blood Sugar (FBS)", keywords=["fbs"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Postprandial Blood Sugar (PPBS)", keywords=["ppbs"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Insulin", keywords=["insulin"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Thyroid Stimulating Hormone (TSH)", keywords=["tsh"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Free T3", keywords=["free t3"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Free T4", keywords=["free t4"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Liver Function Test (LFT)", keywords=["lft"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Alanine Aminotransferase (ALT)", keywords=["alt"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Aspartate Aminotransferase (AST)", keywords=["ast"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Alkaline Phosphatase (ALP)", keywords=["alp"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Gamma-Glutamyl Transferase (GGT)", keywords=["ggt"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Total Protein", keywords=["total protein"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Albumin", keywords=["albumin"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Globulin", keywords=["globulin"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Bilirubin (Total & Direct)", keywords=["bilirubin", "total bilirubin", "direct bilirubin"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Cholesterol", keywords=["cholesterol"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Triglycerides", keywords=["triglycerides"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="HDL Cholesterol", keywords=["hdl cholesterol"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="LDL Cholesterol", keywords=["ldl cholesterol"], field_type="numeric", section="Biochemistry"),
    TemplateField(field_name="Hepatitis B Surface Antigen (HBsAg)", keywords=["hbsag"], field_type="numeric", section="Microbiology"),
    TemplateField(field_name="Hepatitis C Antibody (HCV)", keywords=["hcv"], field_type="numeric", section="Microbiology"),
    TemplateField(field_name="HIV Antibody", keywords=["hiv antibody"], field_type="numeric", section="Microbiology"),
    TemplateField(field_name="Blood Culture", keywords=["blood culture"], field_type="numeric", section="Microbiology"),
    TemplateField(field_name="Urine Culture", keywords=["urine culture"], field_type="numeric", section="Microbiology")
]

# Define test names as a separate list (unchanged)
test_names: List[str] = [
    "Complete Blood Count", "RBC Count", "Hemoglobin", "Packed Cell Volume", "Mean Platelet Volume (MPV)"
    "Platelet Count", "Neutrophils", "Lymphocytes", "Eosinophils", "Monocytes", 
    "Basophils", "Mylocytes", "Blast", "Metamylocytes", "INR", "White Blood Cell Count (WBC)",
    "Mean Corpuscular Volume (MCV)", "Mean Corpuscular Hemoglobin (MCH)", 
    "Mean Corpuscular Hemoglobin Concentration (MCHC)", "Reticulocyte Count", "Hemoglobin A1c",
    "Peripheral Blood Smear", "Blood Film Examination", "Erythrocyte Sedimentation Rate (ESR)", 
    "C-Reactive Protein (CRP)", "Platelet Distribution Width (PDW)", "Platelet Crit (PCT)", 
    "Pancytopenia", "Bone Marrow Aspiration", "Lactate Dehydrogenase (LDH)", "Haptoglobin", 
    "Vitamin B12", "Folate", "Iron Studies", "Serum Iron", "Ferritin", "Total Iron Binding Capacity (TIBC)",
    "Transferrin Saturation", "Sodium", "Potassium", "Chloride", "Calcium", "Magnesium", "Phosphate", 
    "Urea", "Creatinine", "Uric Acid", "Glucose", "Random Blood Sugar (RBS)", "Fasting Blood Sugar (FBS)", 
    "Postprandial Blood Sugar (PPBS)", "Insulin", "Thyroid Stimulating Hormone (TSH)", "Free T3", "Free T4",
    "Liver Function Test (LFT)", "Alanine Aminotransferase (ALT)", "Aspartate Aminotransferase (AST)", 
    "Alkaline Phosphatase (ALP)", "Gamma-Glutamyl Transferase (GGT)", "Total Protein", "Albumin", "Globulin", 
    "Bilirubin (Total & Direct)", "Cholesterol", "Triglycerides", "HDL Cholesterol", "LDL Cholesterol",
    "Hepatitis B Surface Antigen (HBsAg)", "Hepatitis C Antibody (HCV)", "HIV Antibody", "Blood Culture", 
    "Urine Culture"
]
